apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: go-hello-pipeline
spec:
  params:
    - name: repo-url
      type: string
    - name: app-name
      type: string

  workspaces:
    - name: shared-workspace

  tasks:
    - name: clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build
      runAfter: ["clone"]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc start-build $(params.app-name) --wait

    - name: deploy
      runAfter: ["build"]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc rollout restart deployment/$(params.app-name)

    - name: test
      runAfter: ["deploy"]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            sleep 10
            ROUTE=$(oc get route $(params.app-name) -o jsonpath='{.spec.host}')
            curl http://$ROUTE/health
